name: automation

on:
  push:
    branches:
      - fix/iSM996

  workflow_dispatch:

jobs:
  pipeline:
    runs-on: self-hosted
    timeout-minutes: 1200

    steps:
    - name: Clone repository
      run: |
        rm -rf latest-ecModels
        git clone https://github.com/MetabolicAtlas/ecModels latest-ecModels

    - name: Run the pipeline
      run: |
        cd latest-ecModels
        git checkout fix/iSM996
        python3 run.py
