name: automation

on:
  push:
    branches-ignore:
      - 'master'
      - 'main'
      - 'update/**'

  workflow_dispatch:

jobs:
  pipeline:
    runs-on: self-hosted
    timeout-minutes: 1200

    steps:
    - name: Clone repository on current branch
      run: |
        rm -rf *
        git clone https://github.com/$GITHUB_REPOSITORY --branch ${GITHUB_REF#refs/heads/} latest-ecModels

    - name: Run the pipeline
      run: |
        cd latest-ecModels
        python3 run.py ${GITHUB_REF#refs/heads/}