name: automation

on:
  push:
    branches:
      - feat/updated-models

  workflow_dispatch:

jobs:
  pipeline:
    runs-on: self-hosted

    steps:
    - name: Clone repository
      run: |
        rm -rf latest-ecModels
        git clone https://github.com/MetabolicAtlas/ecModels latest-ecModels

    - name: Run the pipeline
      run: |
        cd latest-ecModels
        git checkout feat/updated-models
        python3 run.py